PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX VideOWL: <http://www.semanticweb.org/porta/ontologies/2022/5/VideOWL#>
PREFIX unt: <http://www.semanticweb.org/porta/ontologies/2022/5/untitled-ontology-7#>


1) Retrieve all games that exhibit a distinct narrative (e.g., "emergent").
SELECT DISTINCT ?Game 
               WHERE {
                                   ?Game unt:hasNarrative ?Narration. 
                                   ?Game unt:hasGameplay ?Gameplay.
                                   FILTER (?Narration = unt:simple)
                                    }
